In [1]:
import numpy as np

In [4]:
K = np.array([[2, -1], 
              [-1, 2]])
np.linalg.eig(K)

(array([3., 1.]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

In [7]:
Q = np.array([[1, 1],
              [1, -1]])
D = np.array([[1, 0],
              [0, 3]])

In [8]:
Q@D@np.linalg.inv(Q)

array([[ 2., -1.],
       [-1.,  2.]])

In [9]:
np.linalg.inv(Q)

array([[ 0.5,  0.5],
       [ 0.5, -0.5]])